import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrainCircuit,Target,BookOpen,BarChart3,ArrowRight,CheckCircle2,Sparkles,MessageCircle,Send,RotateCcw} from 'lucide-react';
import './style.css';

const API='http://localhost:8000/api';
function App(){
 const [learner,setLearner]=useState(null),[name,setName]=useState(''),[dashboard,setDashboard]=useState(null),[topics,setTopics]=useState([]),[topic,setTopic]=useState(''),[quiz,setQuiz]=useState(null),[answers,setAnswers]=useState([]),[done,setDone]=useState(false),[score,setScore]=useState(null),[loading,setLoading]=useState(false),[profileLoading,setProfileLoading]=useState(false),[chatMessages,setChatMessages]=useState([]),[chatInput,setChatInput]=useState(''),[chatLoading,setChatLoading]=useState(false),[conversationId,setConversationId]=useState(null);
 const request=async(url,options)=>{const r=await fetch(url,options);const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.detail||'The service is unavailable.');return body};
 const loadDash=async id=>{try{setDashboard(await request(`${API}/dashboard/${id}`))}catch(error){setError(error.message)}};
 const [error,setError]=useState('');
 useEffect(()=>{request(`${API}/topics`).then(data=>{setTopics(data.topics);setTopic(data.topics[0]||'')}).catch(error=>setError(error.message))},[]);
 const start=async()=>{if(!name.trim())return;setProfileLoading(true);try{setError('');const x=await request(`${API}/learners`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})});setLearner(x);loadDash(x.id)}catch(error){setError(error.message)}finally{setProfileLoading(false)}};
 const beginQuiz=async()=>{setLoading(true);setDone(false);setScore(null);setAnswers([]);try{setError('');setQuiz(await request(`${API}/assessment/start`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({learner_id:learner.id,topic,difficulty:'adaptive',count:5})}))}catch(error){setError(error.message)}finally{setLoading(false)}};
 const submit=async()=>{try{setError('');const result=await request(`${API}/assessment/submit`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({quiz_id:quiz.id,learner_id:learner.id,topic,difficulty:quiz.difficulty,answers})});setScore({correct:Math.round(result.score*quiz.questions.length/100),total:result.total});setDone(true);loadDash(learner.id)}catch(error){setError(error.message)}};
 const sendChat=async(prompt)=>{const message=(prompt||chatInput).trim();if(!message||chatLoading)return;setChatInput('');setChatMessages(items=>[...items,{role:'user',content:message}]);setChatLoading(true);try{setError('');const data=await request(`${API}/chat`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({learner_id:learner.id,message,topic,conversation_id:conversationId})});setConversationId(data.conversation_id);setChatMessages(items=>[...items,data.message]);if(data.quiz){setQuiz(data.quiz);setAnswers([]);setDone(false);setScore(null)}}catch(error){setError(error.message)}finally{setChatLoading(false)}};
 const clearChat=()=>{setChatMessages([]);setConversationId(null)};
 if(!learner)return <main className="shell hero"><div className="glow"/><div className="brand"><BrainCircuit size={34}/><span>AI LearnMate</span></div><h1>Learn smarter.<br/><em>Train personally.</em></h1><p>Adaptive learning, intelligent practice and automated assessment in one learning loop.</p><div className="login"><input placeholder="Enter learner name" value={name} onChange={e=>setName(e.target.value)}/><button onClick={start} disabled={profileLoading||!topics.length}>{profileLoading?'Creating profile…':'Enter Workspace'} <ArrowRight size={18}/></button></div>{error&&<div className="error" role="alert">{error}</div>}<small>Hackathon MVP • Personalized Training • MCQ Intelligence</small></main>;
 return <main className="app"><header><div className="brand"><BrainCircuit/><span>AI LearnMate</span></div><div className="user">{learner.name}</div></header>{error&&<div className="error" role="alert">{error}</div>}<section className="welcome"><div><p className="eyebrow">PERSONAL LEARNING INTELLIGENCE</p><h1>Your learning path, <em>adapted to you.</em></h1><p>Take a diagnostic quiz. Your performance updates the learner model and changes what you should practice next.</p></div><div className="orb"><Sparkles size={38}/></div></section>
 <div className="grid">
 <section className="panel"><div className="paneltitle"><BookOpen/><div><h2>Adaptive Practice</h2><p>Choose a topic and generate your next assessment.</p></div></div><select value={topic} onChange={e=>setTopic(e.target.value)} disabled={!topics.length}>{topics.map(item=><option key={item}>{item}</option>)}</select><button className="primary" onClick={beginQuiz} disabled={loading||!topic}>{loading?'Generating…':'Generate Adaptive MCQs'} <Sparkles size={17}/></button>
 {quiz&&!done&&<div className="quiz">{quiz.questions.map((q,i)=><div className="q" key={q.id}><div className="qhead"><span>Q{i+1}</span><b>{q.difficulty}</b></div><h3>{q.question}</h3><div className="options">{q.options.map((o,j)=><button className={answers[i]===j?'selected':''} onClick={()=>{const a=[...answers];a[i]=j;setAnswers(a)}} key={o}>{String.fromCharCode(65+j)}. {o}</button>)}</div></div>)}<button className="primary" disabled={answers.length!==quiz.questions.length||answers.some(answer=>answer===undefined)} onClick={submit}>Submit Assessment <CheckCircle2 size={17}/></button></div>}
 {done&&<div className="success"><CheckCircle2 size={42}/><h2>{score.correct}/{score.total} correct</h2><p>Your learner model has been updated. Review the explanations below.</p>{quiz.questions.map((q,i)=><div className="explanation" key={q.id}><b>{i+1}. {answers[i]===q.answer?'Correct':'Review this one'}</b><p>{q.explanation}</p></div>)}</div>}
 </section>
 <aside className="panel analytics"><div className="paneltitle"><BarChart3/><div><h2>Learning Intelligence</h2><p>Evidence from your attempts.</p></div></div><div className="metrics"><div><span>Attempts</span><strong>{dashboard?.attempts||0}</strong></div><div><span>Average</span><strong>{dashboard?.average_score||0}%</strong></div></div><h3>Topic mastery</h3>{Object.entries(dashboard?.mastery||{}).map(([t,s])=><div className="mastery" key={t}><div><span>{t}</span><b>{s}%</b></div><div className="bar"><i style={{width:`${s}%`}}/></div></div>)}<h3>Learning path</h3>{(dashboard?.learning_path||[]).map(item=><div className="recommend" key={item.topic}><BookOpen/><div><b>{item.topic}</b><p>{item.mastery===null?'Diagnostic needed':`${item.mastery}% mastery · ${item.action}`}</p></div></div>)}<h3>Next best actions</h3>{(dashboard?.recommendations||[]).map(r=><div className="recommend" key={r.topic}><Target/><div><b>{r.topic}</b><p>{r.reason}</p></div></div>)}</aside></div>
 <section className="chat-panel panel"><div className="paneltitle"><MessageCircle/><div><h2>AI Tutor</h2><p>Ask for an explanation, example, hint, or adaptive test.</p></div><button className="icon-button" onClick={clearChat} title="Clear conversation"><RotateCcw size={17}/></button></div><div className="chat-context">Context: {topic || 'loading topic'} · personalized to {learner.name}</div><div className="prompt-row"><button onClick={()=>sendChat('Explain simply')}>Explain simply</button><button onClick={()=>sendChat('Give an example')}>Give example</button><button onClick={()=>sendChat('Give me a hint')}>Hint</button><button onClick={()=>sendChat('Test me')}>Test me</button></div><div className="chat-messages">{chatMessages.length===0&&<div className="chat-empty">Try “Explain inheritance simply” or “Test me with 5 difficult questions.”</div>}{chatMessages.map((message,index)=><div className={`message ${message.role}`} key={`${message.role}-${index}`}><span>{message.role==='user'?'You':'Tutor'}</span><p>{message.content}</p></div>)}{chatLoading&&<div className="message assistant typing"><span>Tutor</span><p>Thinking...</p></div>}</div><div className="chat-compose"><input value={chatInput} onChange={event=>setChatInput(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')sendChat()}} placeholder="Ask your tutor..." disabled={chatLoading}/><button onClick={()=>sendChat()} disabled={chatLoading||!chatInput.trim()} title="Send message"><Send size={17}/></button></div></section>
 <footer><span>AI LearnMate • prototype for Smart Education</span><span>Human review recommended for high-stakes assessment</span></footer></main>
}
createRoot(document.getElementById('root')).render(<App/>);
