import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrainCircuit,Target,BookOpen,BarChart3,ArrowRight,CheckCircle2,Sparkles,MessageCircle,Send,RotateCcw,Upload,Link as LinkIcon,FileText,ExternalLink,Bot,Globe2,WandSparkles,Copy,Check,History,MessageSquareText} from 'lucide-react';
import './style.css';

const API=`${import.meta.env.VITE_API_URL || 'http://127.0.0.1:8000'}/api`;

function renderMessage(content,onCopy){
 const parts=(content||'').split(/(```[\s\S]*?```)/g);
 return <div className="message-content">{parts.map((part,index)=>{
  if(part.startsWith('```')){
   const match=part.match(/^```([^\n]*)\n?/); const language=(match?.[1]||'text').trim();
   const clean=part.replace(/^```[^\n]*\n?/,'').replace(/```$/,'').trimEnd();
   return <div className={`code-block language-${language.toLowerCase()}`} key={index}><div className="code-language">{language}</div><button className="copy-code" onClick={()=>onCopy(clean)}><Copy size={13}/> Copy</button><pre><code>{clean}</code></pre></div>;
  }
  return <p key={index}>{part}</p>;
 })}</div>;
}

function App(){
 const [learner,setLearner]=useState(null),[name,setName]=useState(''),[dashboard,setDashboard]=useState(null),[topics,setTopics]=useState([]),[topic,setTopic]=useState(''),[quiz,setQuiz]=useState(null),[answers,setAnswers]=useState([]),[quizIndex,setQuizIndex]=useState(0),[selectedOption,setSelectedOption]=useState(null),[done,setDone]=useState(false),[score,setScore]=useState(null),[loading,setLoading]=useState(false),[profileLoading,setProfileLoading]=useState(false),[chatMessages,setChatMessages]=useState([]),[chatInput,setChatInput]=useState(''),[chatLoading,setChatLoading]=useState(false),[conversationId,setConversationId]=useState(null),[conversationHistory,setConversationHistory]=useState([]),[historyLoading,setHistoryLoading]=useState(false),[materials,setMaterials]=useState([]),[materialId,setMaterialId]=useState(null),[materialFile,setMaterialFile]=useState(null),[materialQuestionCount,setMaterialQuestionCount]=useState(10),[igotUrl,setIgotUrl]=useState(''),[materialBusy,setMaterialBusy]=useState(false),[materialMessage,setMaterialMessage]=useState('');
 const [error,setError]=useState(''); const [copied,setCopied]=useState(false); const chatMessagesRef=useRef(null);
 const request=async(url,options={})=>{try{const r=await fetch(url,{...options,headers:{...(options.headers||{})}});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.detail||body.message||`Request failed (${r.status})`);return body}catch(error){throw new Error(error.message||'The service is unavailable.')}};
 useEffect(()=>{if(chatMessagesRef.current)chatMessagesRef.current.scrollTo({top:chatMessagesRef.current.scrollHeight,behavior:'smooth'})},[chatMessages,chatLoading]);
 const loadDash=async id=>{try{setDashboard(await request(`${API}/dashboard/${id}`))}catch(error){setError(error.message)}};
 const loadMaterials=async id=>{try{const data=await request(`${API}/materials/${id}`);setMaterials(data.materials);if(data.materials.length&&!materialId)setMaterialId(data.materials[0].id)}catch(error){setError(error.message)}};
 const loadConversationHistory=async id=>{if(!id)return;setHistoryLoading(true);try{const data=await request(`${API}/conversations/${id}`);setConversationHistory(data.conversations||[])}catch(error){setError(error.message)}finally{setHistoryLoading(false)}};
 useEffect(()=>{request(`${API}/topics`).then(data=>{setTopics(data.topics);setTopic(data.topics[0]||'')}).catch(error=>setError(error.message))},[]);
 const start=async()=>{if(!name.trim())return;setProfileLoading(true);try{setError('');const x=await request(`${API}/learners`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})});setLearner(x);loadDash(x.id);loadMaterials(x.id);loadConversationHistory(x.id)}catch(error){setError(error.message)}finally{setProfileLoading(false)}};
 const prepareQuiz=quizData=>{setQuiz(quizData);setAnswers([]);setQuizIndex(0);setSelectedOption(null);setDone(false);setScore(null)};
 const beginQuiz=async()=>{setLoading(true);try{setError('');prepareQuiz(await request(`${API}/assessment/start`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({learner_id:learner.id,topic,difficulty:'adaptive',count:5})}))}catch(error){setError(error.message)}finally{setLoading(false)}};
 const beginMaterialQuiz=async(id=materialId,count=materialQuestionCount)=>{if(!id)return;setLoading(true);setMaterialMessage(`Reading the document and generating ${count} source-grounded MCQs with GPT-5.6 Luna…`);try{setError('');const data=await request(`${API}/materials/${id}/quiz`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({learner_id:learner.id,topic:topic||'Material Assessment',difficulty:'adaptive',count:Number(count)})});prepareQuiz(data);setMaterialMessage(`Quiz ready: ${data.questions.length} questions generated from the document.`)}catch(error){setError(error.message);setMaterialMessage(`Could not generate the document quiz: ${error.message}`)}finally{setLoading(false)}};
 const chooseAnswer=index=>{if(done)return;setSelectedOption(index);const a=[...answers];a[quizIndex]=index;setAnswers(a)};
 const nextQuestion=()=>{if(selectedOption===null)return;if(quizIndex<quiz.questions.length-1){setQuizIndex(i=>i+1);setSelectedOption(answers[quizIndex+1]??null)}else submit()};
 const restartQuiz=()=>{if(!quiz)return;setAnswers([]);setQuizIndex(0);setSelectedOption(null);setDone(false);setScore(null)};
 const submit=async()=>{try{setError('');const result=await request(`${API}/assessment/submit`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({quiz_id:quiz.id,learner_id:learner.id,topic,difficulty:quiz.difficulty,answers})});setScore({correct:Math.round(result.score*quiz.questions.length/100),total:result.total});setDone(true);setSelectedOption(null);loadDash(learner.id)}catch(error){setError(error.message)}};
 const sendChat=async(prompt,forcedMaterialId=null)=>{const message=(prompt||chatInput).trim();if(!message||chatLoading||!learner)return;const activeMaterialId=forcedMaterialId??materialId;setChatInput('');setChatMessages(items=>[...items,{role:'user',content:message}]);setChatLoading(true);try{setError('');const data=await request(`${API}/chat`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({learner_id:learner.id,message,topic,conversation_id:conversationId,material_id:activeMaterialId})});setConversationId(data.conversation_id);setChatMessages(items=>[...items,data.message]);if(data.quiz)prepareQuiz(data.quiz);await loadConversationHistory(learner.id)}catch(error){setError(error.message);setChatMessages(items=>[...items,{role:'assistant',content:'I could not reach the AI assistant right now. Please try again in a moment.'}])}finally{setChatLoading(false)}};
 const uploadMaterial=async()=>{if(!materialFile)return;setMaterialBusy(true);setMaterialMessage('Uploading and extracting readable text…');try{setError('');const form=new FormData();form.append('learner_id',learner.id);form.append('file',materialFile);const data=await request(`${API}/materials/upload`,{method:'POST',body:form});setMaterialFile(null);await loadMaterials(learner.id);setMaterialId(data.id);await beginMaterialQuiz(data.id,materialQuestionCount)}catch(error){setError(error.message);setMaterialMessage(`Document processing failed: ${error.message}`)}finally{setMaterialBusy(false)}};
 const importIgot=async()=>{if(!igotUrl.trim())return;setMaterialBusy(true);setMaterialMessage('Importing and extracting readable text…');try{setError('');const data=await request(`${API}/materials/igot?learner_id=${learner.id}&url=${encodeURIComponent(igotUrl.trim())}`,{method:'POST'});setIgotUrl('');await loadMaterials(learner.id);setMaterialId(data.id);await beginMaterialQuiz(data.id,materialQuestionCount)}catch(error){setError(error.message);setMaterialMessage(`Material processing failed: ${error.message}`)}finally{setMaterialBusy(false)}};
 const openConversation=async id=>{if(!id)return;try{setError('');const data=await request(`${API}/conversations/${id}/messages?learner_id=${learner.id}`);setConversationId(id);setChatMessages(data.messages||[]);if(data.topic)setTopic(data.topic)}catch(error){setError(error.message)}};
 const clearChat=()=>{setChatMessages([]);setConversationId(null);setError('')}; const copyText=async text=>{try{await navigator.clipboard.writeText(text);setCopied(true);setTimeout(()=>setCopied(false),1200)}catch{}}; const providerLabel=provider=>provider==='fallback'?'Local backup':'AI generated';
 if(!learner)return <main className="shell hero"><div className="glow"/><div className="brand"><BrainCircuit size={34}/><span>AI LearnMate</span></div><h1>Learn smarter.<br/><em>Train personally.</em></h1><p>AI-powered personalized learning, material-grounded assessments and competency-focused practice.</p><div className="login"><input placeholder="Enter learner name" value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')start()}}/><button onClick={start} disabled={profileLoading}>{profileLoading?'Creating profile…':'Enter Workspace'} <ArrowRight size={18}/></button></div>{error&&<div className="error" role="alert">{error}</div>}<small>SIH26101 • Smart Education • AI LearnMate</small></main>;
 const currentQuestion=quiz?.questions?.[quizIndex]; const hasAnswer=selectedOption!==null; const currentCorrect=hasAnswer&&currentQuestion&&selectedOption===currentQuestion.answer;
 return <main className="app"><header><div className="brand"><BrainCircuit/><span>AI LearnMate</span></div><div className="user">{learner.name}</div></header>{error&&<div className="error" role="alert">{error}</div>}<section className="welcome"><div><p className="eyebrow">SIH26101 • PERSONALIZED CAPACITY BUILDING</p><h1>Your learning path, <em>adapted to you.</em></h1><p>Upload learning material or connect a public iGOT Karmayogi resource, then let the AI assistant explain, search, calculate, personalize practice and close competency gaps.</p></div><div className="orb"><Sparkles size={38}/></div></section>
 <section className="panel materials-panel"><div className="paneltitle"><FileText/><div><h2>Document → AI Quiz</h2><p>Upload PDF, DOCX, PPTX, TXT, Markdown, CSV, JSON or HTML. The server extracts readable text, validates it, then sends document-grounded content to GPT-5.6 Luna.</p></div></div><div className="material-actions"><label className="upload-box"><Upload size={18}/><span>{materialFile?materialFile.name:'Choose a learning document'}</span><input type="file" accept=".pdf,.docx,.pptx,.txt,.md,.csv,.json,.html,.htm" onChange={e=>setMaterialFile(e.target.files?.[0]||null)}/></label><select value={materialQuestionCount} onChange={e=>setMaterialQuestionCount(Number(e.target.value))} disabled={materialBusy}><option value={5}>5 questions</option><option value={10}>10 questions</option><option value={15}>15 questions</option><option value={20}>20 questions</option></select><button className="secondary" onClick={uploadMaterial} disabled={!materialFile||materialBusy}>{materialBusy?'Processing → GPT…':'Upload & Generate Quiz'}</button></div><div className="igot-row"><LinkIcon size={17}/><input value={igotUrl} onChange={e=>setIgotUrl(e.target.value)} placeholder="Paste a public iGOT Karmayogi course/resource URL"/><button className="secondary" onClick={importIgot} disabled={!igotUrl.trim()||materialBusy}>Import & Generate Quiz</button><a href="https://igotkarmayogi.gov.in/" target="_blank" rel="noreferrer"><ExternalLink size={17}/></a></div>{materialMessage&&<div className="material-note">{materialMessage}</div>}{materials.length>0&&<div className="material-list">{materials.map(item=><button key={item.id} className={materialId===item.id?'material-card selected':'material-card'} onClick={()=>setMaterialId(item.id)}><FileText size={18}/><span><b>{item.title}</b><small>{item.source_type==='igot'?'iGOT resource':'Uploaded material'} · {item.characters.toLocaleString()} characters</small></span></button>)}</div>}<div className="material-footer"><button className="primary" onClick={()=>beginMaterialQuiz()} disabled={!materialId||loading}>{loading?'Generating…':`Generate ${materialQuestionCount} MCQs from selected material`} <Sparkles size={17}/></button><a href="https://igotkarmayogi.gov.in/" target="_blank" rel="noreferrer">Explore official iGOT Karmayogi <ExternalLink size={14}/></a></div></section>
 <div className="grid"><section className="panel"><div className="paneltitle"><BookOpen/><div><h2>Adaptive Practice</h2><p>Choose a topic and generate your next assessment.</p></div></div><select value={topic} onChange={e=>setTopic(e.target.value)} disabled={!topics.length}>{topics.map(item=><option key={item}>{item}</option>)}</select><button className="primary" onClick={beginQuiz} disabled={loading||!topic}>{loading?'Generating…':'Generate Adaptive MCQs'} <Sparkles size={17}/></button>{quiz&&!done&&currentQuestion&&<div className="quiz"><div className="q"><div className="qhead"><span>Q{quizIndex+1} / {quiz.questions.length}</span><b>{currentQuestion.difficulty} · {providerLabel(currentQuestion.provider)}</b></div><h3>{currentQuestion.question}</h3><div className="options">{currentQuestion.options.map((o,j)=><button className={selectedOption===j?'selected':''} disabled={hasAnswer} onClick={()=>chooseAnswer(j)} key={`${currentQuestion.id}-${j}`}>{String.fromCharCode(65+j)}. {o}</button>)}</div>{hasAnswer&&<div className={currentCorrect?'success':'error'} role="status"><b>{currentCorrect?'✓ Correct':'✗ Incorrect'}</b>{!currentCorrect&&<span> Correct answer: {currentQuestion.options[currentQuestion.answer]}</span>}<p>{currentQuestion.explanation}</p></div>}<button className="primary" disabled={!hasAnswer} onClick={nextQuestion}>{quizIndex===quiz.questions.length-1?'Finish Quiz':'Next Question'} <ArrowRight size={17}/></button></div></div>}{done&&<div className="success"><CheckCircle2 size={42}/><h2>{score.correct}/{score.total} correct</h2><p>Your competency profile has been updated.</p><button className="primary" onClick={restartQuiz}><RotateCcw size={17}/> Restart Quiz</button>{quiz.questions.map((q,i)=><div className="explanation" key={q.id}><b>{i+1}. {answers[i]===q.answer?'Correct':'Review this one'} · Correct answer: {q.options[q.answer]}</b><p>{q.explanation}</p></div>)}</div>}</section><aside className="panel analytics"><div className="paneltitle"><BarChart3/><div><h2>Learning Intelligence</h2><p>Evidence from your attempts and competency gaps.</p></div></div><div className="metrics"><div><span>Attempts</span><strong>{dashboard?.attempts||0}</strong></div><div><span>Average</span><strong>{dashboard?.average_score||0}%</strong></div></div><h3>Topic mastery</h3>{Object.entries(dashboard?.mastery||{}).map(([t,s])=><div className="mastery" key={t}><div><span>{t}</span><b>{s}%</b></div><div className="bar"><i style={{width:`${s}%`}}/></div></div>)}<h3>Learning path</h3>{(dashboard?.learning_path||[]).map(item=><div className="recommend" key={item.topic}><BookOpen/><div><b>{item.topic}</b><p>{item.mastery===null?'Diagnostic needed':`${item.mastery}% mastery · ${item.action}`}</p></div></div>)}<h3>Next best actions</h3>{(dashboard?.recommendations||[]).map(r=><div className="recommend" key={r.topic}><Target/><div><b>{r.topic}</b><p>{r.reason}</p></div></div>)}</aside></div>
 <section className="chat-panel panel"><div className="agent-header"><div className="agent-title"><span className="agent-avatar"><Bot size={20}/></span><div><div className="agent-name-row"><h2>AI LearnMate Assistant</h2><span className="live-badge"><i/> LIVE</span></div><p>GPT-5.6 Luna · conversational learning assistant</p></div></div><button className="icon-button" onClick={clearChat} title="New conversation"><RotateCcw size={17}/></button></div><div className="agent-capabilities"><span><Sparkles size={13}/> Teach</span><span><Globe2 size={13}/> Web-aware</span><span><WandSparkles size={13}/> Personalize</span><span><BookOpen size={13}/> Material Q&A</span><span><Target size={13}/> Practice</span></div><div className="chat-context">{learner.name} · {topic||'loading topic'}{materialId?' · selected learning material':''}</div><div className="prompt-row"><button onClick={()=>sendChat('Explain the current topic simply')}>Explain</button><button onClick={()=>sendChat('Make me a personalized study plan')}>Study plan</button><button onClick={()=>sendChat('Analyze my progress and tell me what to practice next')}>My progress</button><button onClick={()=>sendChat('Test me with 5 questions')}>Test me</button></div>
 <div className="chat-history"><aside className="history-panel"><div className="history-title"><span><History size={13}/> Conversation history</span><small>{historyLoading?'Loading…':`${conversationHistory.length} chats`}</small></div>{conversationHistory.length===0?<div className="history-empty">Your saved conversations will appear here after your first message.</div>:conversationHistory.map(item=><button key={item.id} className={conversationId===item.id?'history-item selected':'history-item'} onClick={()=>openConversation(item.id)}><b>{item.title}</b><small>{item.topic||'General'} · {new Date(item.updated_at).toLocaleString()}</small></button>)}</aside><div className="chat-main"><div className="chat-messages" ref={chatMessagesRef}>{chatMessages.length===0&&<div className="chat-empty-agent"><span className="agent-empty-icon"><MessageSquareText size={24}/></span><h3>Ask anything.</h3><p>I can explain concepts, solve problems, debug code, continue follow-ups, use your progress, read selected material, search current information, and create practice when you ask.</p></div>}{chatMessages.map((message,index)=><div className={`message ${message.role}`} key={`${message.id||message.role}-${index}`}><span className="message-label">{message.role==='user'?'You':'AI Assistant'}</span>{renderMessage(message.content,copyText)}{message.role==='assistant'&&<button className="copy-answer" onClick={()=>copyText(message.content)} title="Copy answer">{copied?<Check size={13}/>:<Copy size={13}/>}</button>}</div>)}{chatLoading&&<div className="message assistant typing"><span className="message-label">AI Assistant</span><div className="thinking"><i/><i/><i/><span>Thinking…</span></div></div>}</div><div className="chat-compose"><textarea value={chatInput} onChange={event=>setChatInput(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();sendChat()}}} placeholder="Message AI LearnMate… (Enter to send, Shift+Enter for a new line)" disabled={chatLoading}/><button onClick={()=>sendChat()} disabled={chatLoading||!chatInput.trim()} title="Send message"><Send size={17}/></button></div><small className="agent-disclaimer">AI can make mistakes. Verify important academic or factual information.</small></div></div></section>
 <footer><span>AI LearnMate • SIH26101 Smart Education prototype</span><span>OpenAI-powered conversational assistant • Human review recommended for high-stakes assessment</span></footer></main>
}
createRoot(document.getElementById('root')).render(<App/>);
